pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building application....'
            }
        }
    }
   stages {
        stage('Test') {
            steps {
                echo 'Testing application....'
            }
        }
    }
   stages {
        stage('Deploy') {
            steps {
                echo 'Deploing application....'
            }
        }
    }
}
